name: test-if
on: 
  push:
    branches:
      - dev
      - test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run if main branch
        if: github.ref =='refs/heads/main'
        run: echo "this is main"
      - name: run this step
        run: echo "this is manual"
